# Generated by Django 5.2.10 on 2026-01-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIModelArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="default", max_length=100, unique=True),
                ),
                ("data", models.BinaryField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Model Artifact",
                "verbose_name_plural": "AI Model Artifacts",
            },
        ),
        migrations.CreateModel(
            name="BlacklistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(db_index=True, unique=True),
                ),
                ("reason", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DynamicKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100, unique=True)),
                ("count", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-count"],
            },
        ),
        migrations.CreateModel(
            name="GeoBlockedCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(db_index=True, max_length=2, unique=True),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Geo Blocked Country",
                "verbose_name_plural": "Geo Blocked Countries",
            },
        ),
        migrations.CreateModel(
            name="IPExemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(db_index=True, unique=True),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeatureSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(db_index=True)),
                ("path_len", models.IntegerField()),
                ("kw_hits", models.IntegerField()),
                ("resp_time", models.FloatField()),
                ("status_idx", models.IntegerField()),
                ("burst_count", models.IntegerField()),
                ("total_404", models.IntegerField()),
                ("label", models.CharField(default="unlabeled", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "WAF Feature Sample",
                "verbose_name_plural": "WAF Feature Samples",
                "indexes": [
                    models.Index(fields=["ip"], name="aiwaf_featu_ip_b13d42_idx"),
                    models.Index(
                        fields=["created_at"], name="aiwaf_featu_created_6cae85_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=500)),
                ("status_code", models.IntegerField()),
                ("response_time", models.FloatField()),
                ("user_agent", models.TextField(blank=True, default="")),
                ("referer", models.CharField(blank=True, default="", max_length=500)),
                (
                    "content_length",
                    models.CharField(blank=True, default="-", max_length=20),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Request Log",
                "verbose_name_plural": "Request Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["ip_address"], name="aiwaf_reque_ip_addr_532f7c_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="aiwaf_reque_timesta_be3eb8_idx"
                    ),
                    models.Index(
                        fields=["status_code"], name="aiwaf_reque_status__0ae562_idx"
                    ),
                    models.Index(
                        fields=["method"], name="aiwaf_reque_method_e268ac_idx"
                    ),
                ],
            },
        ),
    ]
