# Generated by Django 5.2.10 on 2026-02-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aiwaf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExemptPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=500, unique=True)),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exempt Path",
                "verbose_name_plural": "Exempt Paths",
            },
        ),
    ]
