# Generated by Django 5.2.11 on 2026-02-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aiwaf", "0002_exemptpath"),
    ]

    operations = [
        migrations.AddField(
            model_name="blacklistentry",
            name="extended_request_info",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
